=== themarioga/CCLH-Commons/src/test/resources/schema.dtd
<!ELEMENT dataset (
    T_CARD*,
    T_CONFIGURATION*,
    T_DICTIONARY*,
    T_GAME*,
    T_TABLE*,
    T_PLAYER*,
    T_ROOM*,
    T_USER*)>

<!ELEMENT T_CARD EMPTY>
<!ATTLIST T_CARD
    TYPE CDATA #REQUIRED
    DICTIONARY_ID CDATA #IMPLIED
    ID CDATA #REQUIRED
    TEXT CDATA #REQUIRED
>

<!ELEMENT T_CONFIGURATION EMPTY>
<!ATTLIST T_CONFIGURATION
    CONF_KEY CDATA #REQUIRED
    CONF_VALUE CDATA #REQUIRED
>

<!ELEMENT T_DICTIONARY EMPTY>
<!ATTLIST T_DICTIONARY
    PUBLISHED CDATA #REQUIRED
    SHARED CDATA #REQUIRED
    CREATOR_ID CDATA #IMPLIED
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

<!ELEMENT T_GAME EMPTY>
<!ATTLIST T_GAME
    ID CDATA #IMPLIED
    ROOM_ID CDATA #REQUIRED
    CREATOR_ID CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    PUNCTUATION_TYPE CDATA #REQUIRED
    STATUS CDATA #REQUIRED
    DICTIONARY_ID CDATA #REQUIRED
    N_CARDS_TO_WIN CDATA #REQUIRED
    N_OF_ROUNDS CDATA #REQUIRED
    N_PLAYERS CDATA #IMPLIED
>

<!ELEMENT T_TABLE EMPTY>
<!ATTLIST T_TABLE
    GAME_ID CDATA #REQUIRED
    STATUS CDATA #REQUIRED
    ROUND_NUMBER CDATA #REQUIRED
    BLACKCARD_ID CDATA #IMPLIED
    PRESIDENT_ID CDATA #IMPLIED
>

<!ELEMENT T_PLAYER EMPTY>
<!ATTLIST T_PLAYER
    ID CDATA #REQUIRED
    JOIN_ORDER CDATA #REQUIRED
    POINTS CDATA #IMPLIED
    GAME_ID CDATA #REQUIRED
    USER_ID CDATA #REQUIRED
>

<!ELEMENT T_ROOM EMPTY>
<!ATTLIST T_ROOM
    ACTIVE CDATA #REQUIRED
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

<!ELEMENT T_USER EMPTY>
<!ATTLIST T_USER
    ACTIVE CDATA #REQUIRED
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

=== themarioga/CCLH-Commons/src/test/resources/dbunit/service/setup/card.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dataset SYSTEM "src/test/resources/schema.dtd">
<dataset>
    <T_CARD ID="0" TEXT="First black card" TYPE="0" DICTIONARY_ID="0"/>
    <T_CARD ID="1" TEXT="Second black card" TYPE="0" DICTIONARY_ID="0"/>
    <T_CARD ID="2" TEXT="Third black card" TYPE="0" DICTIONARY_ID="0"/>
    <T_CARD ID="3" TEXT="First white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="4" TEXT="Second white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="5" TEXT="Third white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="6" TEXT="Fourth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="7" TEXT="Fifth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="8" TEXT="Sixth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="9" TEXT="Seventh white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="10" TEXT="Eighth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="11" TEXT="Nineth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="12" TEXT="Tenth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="13" TEXT="Eleventh white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="14" TEXT="Twelveth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="15" TEXT="Thirdteenth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="16" TEXT="Fourthteenth white card" TYPE="1" DICTIONARY_ID="0"/>
    <T_CARD ID="17" TEXT="Fifthteenth white card" TYPE="1" DICTIONARY_ID="0"/>
</dataset>
